/*   BootstrapLeggero (Alpha 0.1) : Light Bootstrap Generator
 * 
 * 	 Copyright (C) 2018 Fabio Solia <solia.fabio@hotmail.it>
 * 	
 *	 This file is part of BootstrapLeggero.
 *
 *   BootstrapLeggero is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   BootstrapLeggero is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with BootstrapLeggero.  If not, see <http://www.gnu.org/licenses/>.
 */

import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import java.awt.event.ActionListener;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.awt.event.ActionEvent;
import javax.swing.JTextPane;
import javax.swing.JLabel;

public class main {

	/* Some parts of code is autogenerated by windowbuilder plugin of Eclipse */
	private JFrame frmBootstrapLeggero;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					main window = new main();
					window.frmBootstrapLeggero.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	public main() {
		initialize();
	}

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		//Frame creations
		frmBootstrapLeggero = new JFrame();
		frmBootstrapLeggero.setResizable(false);
		frmBootstrapLeggero.setTitle("Bootstrap Leggero");
		frmBootstrapLeggero.setBounds(100, 100, 889, 502);
		frmBootstrapLeggero.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

		//Cretion of the labels
		JLabel lblNewLabel = new JLabel("Directory of HTML file");
		lblNewLabel.setBounds(12, 45, 163, 55);
		frmBootstrapLeggero.getContentPane().add(lblNewLabel);

		JLabel lblNewLabel_1 = new JLabel("Directory of Bootstrap File");
		lblNewLabel_1.setBounds(12, 227, 163, 55);
		frmBootstrapLeggero.getContentPane().add(lblNewLabel_1);

		//Creation of textboxes
		JTextPane textPane = new JTextPane();
		textPane.setEditable(false);
		textPane.setBounds(232, 45, 332, 55);
		frmBootstrapLeggero.getContentPane().add(textPane);

		JTextPane textPane_1 = new JTextPane();
		textPane_1.setEditable(false);
		textPane_1.setBounds(232, 227, 332, 55);
		frmBootstrapLeggero.getContentPane().add(textPane_1);

		//Creation of buttons
		JButton btnNewButton_1 = new JButton("Choose an HTML file");
		btnNewButton_1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				JFileChooser fileHTMLChooser = new JFileChooser();
				if(fileHTMLChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
					java.io.File HTMLfile = fileHTMLChooser.getSelectedFile();
					String HTMLfileName = HTMLfile.getAbsolutePath();
					textPane.setText(HTMLfileName);
				}
			}
		});
		btnNewButton_1.setBounds(654, 45, 205, 55);
		frmBootstrapLeggero.getContentPane().add(btnNewButton_1);

		JButton btnChooseABootstrap = new JButton("Choose a Bootstrap CSS File");
		btnChooseABootstrap.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				String extension = "";
				JFileChooser fileBootstrapChooser = new JFileChooser();
				if(fileBootstrapChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
					java.io.File fileBootstrap = fileBootstrapChooser.getSelectedFile();
					String fileName=fileBootstrap.getName();
					//Sequence of instructions for verify if the file has an CSS extension
					if(fileName.contains(".") && fileName.lastIndexOf(".")!= 0)
					{
						extension=fileName.substring(fileName.lastIndexOf(".")+1).toUpperCase();
					}
					if(extension.equals("CSS")) {
						String BootstrapfileName = fileBootstrap.getAbsolutePath();
						textPane_1.setText(BootstrapfileName);
					}
					else {
						JOptionPane.showMessageDialog(null, "This is not a CSS file. Choose an another file.");
					}
				}
			}
		});
		btnChooseABootstrap.setBounds(654, 227, 205, 55);
		frmBootstrapLeggero.getContentPane().add(btnChooseABootstrap);

		JButton btnNewButton = new JButton("Generates the lighten bootstrap file");
		btnNewButton.setBounds(320, 387, 270, 55);
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					String txtHTML = textPane.getText();
					String txtBootstrap = textPane_1.getText();
					//Verify if the textboxes don't are empty
					if(txtHTML.trim().isEmpty() || txtBootstrap.trim().isEmpty()) 
					{
						JOptionPane.showMessageDialog(null, "File directories can not be undetected!");
					}
					else {
						/* 
						 * Call for classes and methods to do the main actions to generate the lightened bootstrap file
						 * For more information open declared type in your IDE for see the source code
						 */
						ReadHTMLFile readfile = new ReadHTMLFile();
						String line = readfile.mainFile(txtHTML);
						String []lineArray = null;
						String BootstrapLine = null;
						Timestamp timestamp = new Timestamp(System.currentTimeMillis());
						ArrayList<String> listArray = new ArrayList<String>();
						ElaborateBootstrapCSSFile elaborate = new ElaborateBootstrapCSSFile();
						listArray = elaborate.SplitFile(line,lineArray);
						BootstrapLine = elaborate.ReadBootstrapCSSFile(txtBootstrap, listArray);
						elaborate.writing(BootstrapLine,timestamp.getTime() + "-bootstrap.css");
						JOptionPane.showMessageDialog (null, "The file was successfully generated.");
						textPane.setText("");
						textPane_1.setText("");
					}
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog (null, "The application have encountered an internal error and failed to generate the lightened bootstrap file.");
					e1.printStackTrace();
				}
			}
		});
		frmBootstrapLeggero.getContentPane().setLayout(null);
		frmBootstrapLeggero.getContentPane().add(btnNewButton);
	}
}
